name: build

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.xaml'

env:
  Solution_Name: MrSquashWatcher.sln
  Test_Project_Path: MrSquash.Tests\MrSquash.Tests.csproj
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3

    # Install the .NET Core workload
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    # Install dependencies
    - name: Install dependencies
      run: dotnet restore

    # Build
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Execute all unit tests in the solution
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
