name: Deploy release

on:
  push:
    branches: [ master ]
    tags:
    - 'releases/v*'

env:
  PROJECT_ID: 'MrSquashWatcher'
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test --no-build -c Release

    - name: Publish
      run: dotnet publish --no-build -c Release --self-contained true -p:Version=${{ github.ref }} -p:TargetFramework=net8.0-windows10.0.17763.0
    
    # - name: Create Velopack Release
      # run: |
        # dotnet tool install -g vpk
        # vpk download github --repoUrl https://github.com/${{ github.repository }}
        # vpk pack -u ${{ env.PROJECT_ID }} -v ${{ github.ref }} -p publish
        # vpk upload github --repoUrl https://github.com/${{ github.repository }} --publish --releaseName "${{ env.PROJECT_ID }} ${{ github.ref }}" --tag v${{ github.ref }}
